### ISSUE TITLE
errors on linux

### ISSUE THREAD

**Issue by asfaew** [LagoLunatic/GCFT#23]
Unable to import OpenGL.platform.egl.EGLPlatform: No module named 'OpenGL.platform.egl'
Traceback (most recent call last):
  File "gcft.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "gcft_ui/main_window.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "gcft_ui/j3d_tab.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "gcft_ui/uic/ui_j3d_tab.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "gcft_ui/j3d_viewer.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "OpenGL/error.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "OpenGL/platform/__init__.py", line 56, in <module>
  File "OpenGL/platform/__init__.py", line 50, in _load
TypeError: 'NoneType' object is not callable
[PYI-56002:ERROR] Failed to execute script 'gcft' due to unhandled exception!

**Comment by asfaew** [comment]
when i first start it up
ubuntu
latest i think
prebuilt
i dont know

**Comment by LagoLunatic** [comment]
> ubuntu

Which version?

And what display server? X11 or Wayland?

> prebuilt

Yes, but what if you run from source? Is it the same error?

> i dont know

Maybe you should look into that then. The error makes it sound like your computer's missing something opengl related, but I don't know what.

**Comment by NoAccount1** [comment]
I'm facing the same problem, my specs are :
- Archlinux
- KDE Plasma 6.4.2 on Wayland 
- Python 3.13.5
When I tried to run it with the linux build, I got the same error as @asfaew (even tho I installed `python-opengl` package)

When I tried from source, since my python environment is externally managed (quite common I think) I installed every dependency by hand and struggled a bit with `imagequant` which isn't available in any of my repos
But finally it somehow ran with this error :
```py
Traceback (most recent call last):
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft.py", line 10, in <module>
    from gcft_ui.main_window import GCFTWindow
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/main_window.py", line 17, in <module>
    from gcft_ui.gcm_tab import GCMTab
  File "[home_directory]/Jeux/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/gcm_tab.py", line 14, in <module>
    from asset_dumper import AssetDumper
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/asset_dumper.py", line 8, in <module>
    from gclib.j3d import J3D
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/../gclib/gclib/j3d.py", line 4, in <module>
    from gclib.jchunk import JChunk
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/../gclib/gclib/jchunk.py", line 4, in <module>
    from gclib.bunfoe import bunfoe, field, BUNFOE
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/../gclib/gclib/bunfoe.py", line 36, in <module>
    class Field(dataclasses.Field):
    ...<53 lines>...
                ')')
  File "[home_directory]/gcft-2.0.0-linux/tmp/GCFT/gcft_ui/../gclib/gclib/bunfoe.py", line 68, in Field
    @dataclasses._recursive_repr
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dataclasses' has no attribute '_recursive_repr'. Did you mean: 'recursive_repr'?```

**Comment by LagoLunatic** [comment]
The _recursive_repr issue: This is because you used a different python version from what's specified in the readme. GCFT only works on Python 3.12 and I haven't tested it on 3.13, so you're supposed to use something like uv to run with a different python version separate from your system's managed python installation. I can try to see if I can add 3.13 support at some point but it won't be trivial as that version changed quite a few things that GCFT uses. Just removing that one underscore like you did is not enough to fix all of the version differences and you will definitely run into more problems, so I don't recommend using the wrong Python version at all.

For imagequant: I don't understand what issues you're having with that? It's on PyPI and even supports 3.13, so just using pip to install requirements.txt as normal should install that fine.

As for the main issue with the prebuilt executable not working because of OpenGL, I have no idea what's going on there. Never seen an issue similar to that. I'm on Linux Mint with Cinnamon 6.4.8 on X11. Wonder if it just doesn't work on Arch Linux? For the time being I updated which version of PyOpenGL is used by the prebuilt executable, can you test if this works or if it gives the same error as the older PyOpenGL version? https://nightly.link/LagoLunatic/GCFT/actions/runs/16348877103

**Comment by asfaew** [comment]
my linux laptop broke so i dont have to worry about it
